'use client'

import { useState, useEffect, Suspense } from 'react'
import { useSearchParams } from 'next/navigation'
import { ScatterChart, Scatter, XAxis, YAxis, ZAxis, CartesianGrid, Tooltip, ResponsiveContainer, BarChart, Bar, Cell, Legend } from 'recharts'
import { formatCurrency } from '@/lib/utils'

function TrendsContent() {
  const searchParams = useSearchParams()
  const range = searchParams.get('range') || 'All Time'
  
  const [weekdayData, setWeekdayData] = useState<any>(null)
  const [trendsData, setTrendsData] = useState<any>(null)

  useEffect(() => {
    fetch(`/api/revenue/by-weekday?range=${encodeURIComponent(range)}`)
      .then(r => r.json())
      .then(data => setWeekdayData(data))

    fetch(`/api/trends?range=${encodeURIComponent(range)}`)
      .then(r => r.json())
      .then(data => setTrendsData(data))
  }, [range])

  const maxWeekday = Array.isArray(weekdayData) && weekdayData.length > 0 ? Math.max(...weekdayData.map((d: any) => d.revenue)) : 1

  const categoryColors: Record<string, string> = {
    'Electronics': '#8b5cf6',
    'Clothing': '#ec4899',
    'Home & Garden': '#f59e0b',
    'Sports': '#06b6d4',
    'Books': '#64748b'
  }

  const CustomBar = (props: any) => {
    const { fill, x, y, width, height } = props;
    const radius = 6;
    if (height <= 0) return null;
    return (
      <path
        d={`M${x},${y + height} L${x},${y + radius} Q${x},${y} ${x + radius},${y} L${x + width - radius},${y} Q${x + width},${y} ${x + width},${y + radius} L${x + width},${y + height} Z`}
        fill={fill}
      />
    );
  }

  // Generate plain english text for correlation
  let correlationText = "calculating..."
  if (trendsData) {
    const r = trendsData.correlation
    if (Math.abs(r) < 0.2) correlationText = `No significant correlation (${r.toFixed(2)}). Price changes rarely impact volume directly.`
    else if (r > 0.6) correlationText = `Strong positive correlation (${r.toFixed(2)}). Premium items are driving higher volumes.`
    else if (r > 0.2) correlationText = `Weak positive correlation (${r.toFixed(2)}).`
    else if (r < -0.6) correlationText = `Strong negative correlation (${r.toFixed(2)}). Lower prices drive significantly higher volume.`
    else if (r < -0.2) correlationText = `Weak negative correlation (${r.toFixed(2)}).`
  }

  return (
    <>
      <div className="ph" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
        <div>
          <h1 className="pt">Market Trends</h1>
        </div>
      </div>

      <div className="scroll-container">
        <div className="charts-grid">
          <div className="clay-raised chart-card" style={{ gridColumn: 'span 2' }}>
            <div className="chart-title">Best Day to Sell</div>
            <div className="chart-sub">Revenue generated by day of week</div>
            <div style={{ height: 280, marginTop: 16 }}>
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={weekdayData || []}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--clay-surface-raised)" />
                  <XAxis dataKey="day" tick={{ fontSize: 12, fill: 'var(--clay-text-dim)' }} axisLine={false} tickLine={false} />
                  <YAxis tick={{ fontSize: 12, fill: 'var(--clay-text-dim)' }} axisLine={false} tickLine={false} tickFormatter={(v) => `$${v/1000}k`} />
                  <Tooltip cursor={{fill: 'rgba(255,255,255,0.03)'}} contentStyle={{ borderRadius: 12, border: 'none', background: 'var(--clay-surface-raised)', color: 'var(--clay-text)' }} formatter={(value: any) => formatCurrency(value)} />
                  <Bar dataKey="revenue" shape={<CustomBar />}>
                    {(weekdayData || []).map((entry: any, index: number) => {
                      const intensity = 0.3 + (entry.revenue / maxWeekday) * 0.7;
                      return <Cell key={index} fill={`rgba(139, 92, 246, ${intensity})`} />;
                    })}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>

          <div className="clay-raised chart-card">
            <div className="chart-title">Price vs. Quantity</div>
            <div className="chart-sub">Bubble size = Total Revenue</div>
            <div style={{ height: 300, marginTop: 16 }}>
              <ResponsiveContainer width="100%" height="100%">
                <ScatterChart margin={{ top: 20, right: 20, bottom: 20, left: 20 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="var(--clay-surface-raised)" />
                  <XAxis type="number" dataKey="price" name="Price" tick={{ fontSize: 11, fill: 'var(--clay-text-dim)' }} tickFormatter={(v) => `$${v}`} />
                  <YAxis type="number" dataKey="quantity" name="Units" tick={{ fontSize: 11, fill: 'var(--clay-text-dim)' }} />
                  <ZAxis type="number" dataKey="revenue" range={[20, 400]} name="Revenue" />
                  <Tooltip cursor={{strokeDasharray: '3 3'}} contentStyle={{ borderRadius: 12, border: 'none', background: 'var(--clay-surface-raised)', color: 'var(--clay-text)' }} formatter={(value: any, name: any) => name === 'Price' || name === 'Revenue' ? formatCurrency(value) : value} />
                  {/* We map unique categories to distinct scatters so they get colored differently and show in legend */}
                  {trendsData && Array.from(new Set(trendsData.scatter.map((d:any) => d.category))).map((cat: any) => (
                    <Scatter 
                      key={cat} 
                      name={cat} 
                      data={trendsData.scatter.filter((d:any) => d.category === cat)} 
                      fill={categoryColors[cat] || 'var(--clay-accent)'} 
                      opacity={0.8}
                    />
                  ))}
                </ScatterChart>
              </ResponsiveContainer>
            </div>
          </div>

          <div className="clay-raised chart-card">
            <div className="chart-title">Price Distribution</div>
            <div className="chart-sub">Min, Max & Average Price by Category</div>
            <div style={{ marginTop: 24, display: 'flex', flexDirection: 'column', gap: '20px' }}>
              {trendsData ? trendsData.distribution.map((d: any, i: number) => {
                const maxGlobal = Math.max(...trendsData.distribution.map((x:any) => x.max))
                return (
                  <div key={i}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12, marginBottom: 4 }}>
                      <span style={{ color: 'var(--clay-text-dim)' }}>{d.category}</span>
                      <span style={{ fontWeight: 'bold' }}>{formatCurrency(d.avg)} avg</span>
                    </div>
                    <div style={{ position: 'relative', height: 8, background: 'var(--clay-surface-pressed)', borderRadius: 4 }}>
                      <div style={{ 
                        position: 'absolute', 
                        left: `${(d.min / maxGlobal) * 100}%`, 
                        width: `${((d.max - d.min) / maxGlobal) * 100}%`,
                        height: '100%', 
                        background: categoryColors[d.category] || 'var(--clay-accent)', 
                        opacity: 0.6,
                        borderRadius: 4
                      }}></div>
                      {/* Average marker */}
                      <div style={{
                        position: 'absolute',
                        left: `${(d.avg / maxGlobal) * 100}%`,
                        width: 4,
                        height: 12,
                        top: -2,
                        background: 'var(--clay-text)',
                        borderRadius: 2
                      }}></div>
                    </div>
                    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 10, marginTop: 4, color: 'var(--clay-text-dim)' }}>
                      <span>Min: {formatCurrency(d.min)}</span>
                      <span>Max: {formatCurrency(d.max)}</span>
                    </div>
                  </div>
                )
              }) : (
                <div style={{ color: 'var(--clay-text-dim)' }}>Loading...</div>
              )}
            </div>
          </div>

          <div className="clay-raised chart-card" style={{ gridColumn: 'span 2' }}>
            <div className="chart-title">Price-Volume Correlation</div>
            <div className="chart-sub">Are discounts driving volume?</div>
            <div style={{ marginTop: 16, padding: '24px', background: 'var(--clay-surface-pressed)', borderRadius: '16px', border: '1px solid rgba(255,255,255,0.02)' }}>
              <div style={{ fontSize: 24, fontWeight: 'bold', color: 'var(--clay-accent)', marginBottom: 8 }}>
                {trendsData ? (trendsData.correlation * 100).toFixed(1) + '%' : '...'}
              </div>
              <div style={{ fontSize: 16, color: 'var(--clay-text)', lineHeight: 1.5 }}>
                {correlationText}
              </div>
              <div style={{ marginTop: 16, fontSize: 12, color: 'var(--clay-text-dim)' }}>
                Correlation measures how closely price and quantity move together. A value near 0 implies they are independent. 
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

export default function TrendsPage() {
  return (
    <Suspense fallback={<div>Loading Trends...</div>}>
      <TrendsContent />
    </Suspense>
  )
}
