window.rawData = [
  {"Product_ID": 1001, "Product_Name": "Lipstick", "Category": "Beauty", "Price_USD": 26, "Quantity_Sold": 7, "Total_Sales_USD": 182, "Order_Date": "2025-01-24", "Customer_City": "Karachi"},
  {"Product_ID": 1002, "Product_Name": "Jacket", "Category": "Fashion", "Price_USD": 254, "Quantity_Sold": 6, "Total_Sales_USD": 1524, "Order_Date": "2026-04-01", "Customer_City": "Peshawar"},
  {"Product_ID": 1003, "Product_Name": "Gym Gloves", "Category": "Sports", "Price_USD": 30, "Quantity_Sold": 10, "Total_Sales_USD": 300, "Order_Date": "2025-11-05", "Customer_City": "Peshawar"},
  {"Product_ID": 1004, "Product_Name": "History Book", "Category": "Books", "Price_USD": 45, "Quantity_Sold": 6, "Total_Sales_USD": 270, "Order_Date": "2026-01-05", "Customer_City": "Lahore"},
  {"Product_ID": 1005, "Product_Name": "Tennis Ball", "Category": "Sports", "Price_USD": 401, "Quantity_Sold": 1, "Total_Sales_USD": 401, "Order_Date": "2025-11-28", "Customer_City": "Quetta"},
  {"Product_ID": 1006, "Product_Name": "Coffee Mug", "Category": "Home", "Price_USD": 338, "Quantity_Sold": 8, "Total_Sales_USD": 2704, "Order_Date": "2025-06-06", "Customer_City": "Lahore"},
  {"Product_ID": 1007, "Product_Name": "Gym Gloves", "Category": "Sports", "Price_USD": 102, "Quantity_Sold": 8, "Total_Sales_USD": 816, "Order_Date": "2025-06-25", "Customer_City": "Islamabad"},
  {"Product_ID": 1008, "Product_Name": "Gym Gloves", "Category": "Sports", "Price_USD": 394, "Quantity_Sold": 5, "Total_Sales_USD": 1970, "Order_Date": "2026-03-15", "Customer_City": "Islamabad"},
  {"Product_ID": 1009, "Product_Name": "Lipstick", "Category": "Beauty", "Price_USD": 381, "Quantity_Sold": 5, "Total_Sales_USD": 1905, "Order_Date": "2025-02-28", "Customer_City": "Lahore"},
  {"Product_ID": 1010, "Product_Name": "Science Book", "Category": "Books", "Price_USD": 352, "Quantity_Sold": 3, "Total_Sales_USD": 1056, "Order_Date": "2025-04-11", "Customer_City": "Islamabad"},
  {"Product_ID": 1011, "Product_Name": "Wireless Mouse", "Category": "Electronics", "Price_USD": 291, "Quantity_Sold": 10, "Total_Sales_USD": 2910, "Order_Date": "2025-09-02", "Customer_City": "Islamabad"},
  {"Product_ID": 1012, "Product_Name": "Table", "Category": "Home", "Price_USD": 427, "Quantity_Sold": 9, "Total_Sales_USD": 3843, "Order_Date": "2025-07-17", "Customer_City": "Karachi"},
  {"Product_ID": 1013, "Product_Name": "Math Guide", "Category": "Books", "Price_USD": 126, "Quantity_Sold": 1, "Total_Sales_USD": 126, "Order_Date": "2025-08-17", "Customer_City": "Islamabad"},
  {"Product_ID": 1014, "Product_Name": "Lamp", "Category": "Home", "Price_USD": 42, "Quantity_Sold": 2, "Total_Sales_USD": 84, "Order_Date": "2025-09-08", "Customer_City": "Quetta"},
  {"Product_ID": 1015, "Product_Name": "Science Book", "Category": "Books", "Price_USD": 348, "Quantity_Sold": 8, "Total_Sales_USD": 2784, "Order_Date": "2025-12-23", "Customer_City": "Quetta"},
  {"Product_ID": 1016, "Product_Name": "Smart Watch", "Category": "Electronics", "Price_USD": 432, "Quantity_Sold": 4, "Total_Sales_USD": 1728, "Order_Date": "2025-03-20", "Customer_City": "Karachi"},
  {"Product_ID": 1017, "Product_Name": "Science Book", "Category": "Books", "Price_USD": 61, "Quantity_Sold": 4, "Total_Sales_USD": 244, "Order_Date": "2025-12-11", "Customer_City": "Lahore"},
  {"Product_ID": 1018, "Product_Name": "Science Book", "Category": "Books", "Price_USD": 202, "Quantity_Sold": 6, "Total_Sales_USD": 1212, "Order_Date": "2025-01-21", "Customer_City": "Karachi"},
  {"Product_ID": 1019, "Product_Name": "Headphones", "Category": "Electronics", "Price_USD": 250, "Quantity_Sold": 5, "Total_Sales_USD": 1250, "Order_Date": "2026-01-03", "Customer_City": "Quetta"},
  {"Product_ID": 1020, "Product_Name": "Football", "Category": "Sports", "Price_USD": 410, "Quantity_Sold": 5, "Total_Sales_USD": 2050, "Order_Date": "2025-09-25", "Customer_City": "Islamabad"},
  {"Product_ID": 1021, "Product_Name": "Coffee Mug", "Category": "Home", "Price_USD": 210, "Quantity_Sold": 3, "Total_Sales_USD": 630, "Order_Date": "2026-03-05", "Customer_City": "Karachi"},
  {"Product_ID": 1022, "Product_Name": "Face Wash", "Category": "Beauty", "Price_USD": 215, "Quantity_Sold": 1, "Total_Sales_USD": 215, "Order_Date": "2025-05-23", "Customer_City": "Peshawar"},
  {"Product_ID": 1023, "Product_Name": "Perfume", "Category": "Beauty", "Price_USD": 443, "Quantity_Sold": 10, "Total_Sales_USD": 4430, "Order_Date": "2025-10-04", "Customer_City": "Karachi"},
  {"Product_ID": 1024, "Product_Name": "Lamp", "Category": "Home", "Price_USD": 97, "Quantity_Sold": 3, "Total_Sales_USD": 291, "Order_Date": "2025-05-09", "Customer_City": "Peshawar"},
  {"Product_ID": 1025, "Product_Name": "Math Guide", "Category": "Books", "Price_USD": 11, "Quantity_Sold": 6, "Total_Sales_USD": 66, "Order_Date": "2025-06-27", "Customer_City": "Karachi"},
  {"Product_ID": 1026, "Product_Name": "Shoes", "Category": "Fashion", "Price_USD": 144, "Quantity_Sold": 10, "Total_Sales_USD": 1440, "Order_Date": "2025-07-27", "Customer_City": "Karachi"},
  {"Product_ID": 1027, "Product_Name": "History Book", "Category": "Books", "Price_USD": 71, "Quantity_Sold": 6, "Total_Sales_USD": 426, "Order_Date": "2026-01-07", "Customer_City": "Islamabad"},
  {"Product_ID": 1028, "Product_Name": "Gym Gloves", "Category": "Sports", "Price_USD": 104, "Quantity_Sold": 2, "Total_Sales_USD": 208, "Order_Date": "2025-11-10", "Customer_City": "Lahore"},
  {"Product_ID": 1029, "Product_Name": "Coffee Mug", "Category": "Home", "Price_USD": 464, "Quantity_Sold": 4, "Total_Sales_USD": 1856, "Order_Date": "2025-09-16", "Customer_City": "Peshawar"},
  {"Product_ID": 1030, "Product_Name": "Gym Gloves", "Category": "Sports", "Price_USD": 400, "Quantity_Sold": 9, "Total_Sales_USD": 3600, "Order_Date": "2025-06-03", "Customer_City": "Quetta"},
  {"Product_ID": 1031, "Product_Name": "Jacket", "Category": "Fashion", "Price_USD": 292, "Quantity_Sold": 8, "Total_Sales_USD": 2336, "Order_Date": "2025-10-25", "Customer_City": "Karachi"},
  {"Product_ID": 1032, "Product_Name": "Jeans", "Category": "Fashion", "Price_USD": 434, "Quantity_Sold": 3, "Total_Sales_USD": 1302, "Order_Date": "2026-03-07", "Customer_City": "Islamabad"},
  {"Product_ID": 1033, "Product_Name": "Wireless Mouse", "Category": "Electronics", "Price_USD": 465, "Quantity_Sold": 2, "Total_Sales_USD": 930, "Order_Date": "2025-02-17", "Customer_City": "Karachi"},
  {"Product_ID": 1034, "Product_Name": "Math Guide", "Category": "Books", "Price_USD": 209, "Quantity_Sold": 9, "Total_Sales_USD": 1881, "Order_Date": "2026-03-09", "Customer_City": "Islamabad"},
  {"Product_ID": 1035, "Product_Name": "Table", "Category": "Home", "Price_USD": 69, "Quantity_Sold": 9, "Total_Sales_USD": 621, "Order_Date": "2026-03-11", "Customer_City": "Karachi"},
  {"Product_ID": 1036, "Product_Name": "Science Book", "Category": "Books", "Price_USD": 486, "Quantity_Sold": 1, "Total_Sales_USD": 486, "Order_Date": "2025-09-19", "Customer_City": "Quetta"},
  {"Product_ID": 1037, "Product_Name": "Keyboard", "Category": "Electronics", "Price_USD": 115, "Quantity_Sold": 5, "Total_Sales_USD": 575, "Order_Date": "2026-01-24", "Customer_City": "Lahore"},
  {"Product_ID": 1038, "Product_Name": "Headphones", "Category": "Electronics", "Price_USD": 228, "Quantity_Sold": 6, "Total_Sales_USD": 1368, "Order_Date": "2025-06-21", "Customer_City": "Karachi"},
  {"Product_ID": 1039, "Product_Name": "Shoes", "Category": "Fashion", "Price_USD": 48, "Quantity_Sold": 3, "Total_Sales_USD": 144, "Order_Date": "2025-10-14", "Customer_City": "Peshawar"},
  {"Product_ID": 1040, "Product_Name": "Table", "Category": "Home", "Price_USD": 280, "Quantity_Sold": 10, "Total_Sales_USD": 2800, "Order_Date": "2026-02-05", "Customer_City": "Quetta"},
  {"Product_ID": 1041, "Product_Name": "Tennis Ball", "Category": "Sports", "Price_USD": 417, "Quantity_Sold": 10, "Total_Sales_USD": 4170, "Order_Date": "2025-02-04", "Customer_City": "Quetta"},
  {"Product_ID": 1042, "Product_Name": "Gym Gloves", "Category": "Sports", "Price_USD": 94, "Quantity_Sold": 3, "Total_Sales_USD": 282, "Order_Date": "2026-02-18", "Customer_City": "Quetta"},
  {"Product_ID": 1043, "Product_Name": "Gym Gloves", "Category": "Sports", "Price_USD": 491, "Quantity_Sold": 7, "Total_Sales_USD": 3437, "Order_Date": "2025-09-15", "Customer_City": "Islamabad"},
  {"Product_ID": 1044, "Product_Name": "Lipstick", "Category": "Beauty", "Price_USD": 109, "Quantity_Sold": 4, "Total_Sales_USD": 436, "Order_Date": "2026-05-02", "Customer_City": "Islamabad"},
  {"Product_ID": 1045, "Product_Name": "Lipstick", "Category": "Beauty", "Price_USD": 141, "Quantity_Sold": 3, "Total_Sales_USD": 423, "Order_Date": "2025-06-14", "Customer_City": "Karachi"},
  {"Product_ID": 1046, "Product_Name": "Jacket", "Category": "Fashion", "Price_USD": 369, "Quantity_Sold": 5, "Total_Sales_USD": 1845, "Order_Date": "2025-09-23", "Customer_City": "Peshawar"},
  {"Product_ID": 1047, "Product_Name": "Football", "Category": "Sports", "Price_USD": 64, "Quantity_Sold": 8, "Total_Sales_USD": 512, "Order_Date": "2025-04-18", "Customer_City": "Lahore"},
  {"Product_ID": 1048, "Product_Name": "Cricket Bat", "Category": "Sports", "Price_USD": 461, "Quantity_Sold": 9, "Total_Sales_USD": 4149, "Order_Date": "2025-02-08", "Customer_City": "Peshawar"},
  {"Product_ID": 1049, "Product_Name": "Lamp", "Category": "Home", "Price_USD": 356, "Quantity_Sold": 8, "Total_Sales_USD": 2848, "Order_Date": "2025-05-03", "Customer_City": "Peshawar"},
  {"Product_ID": 1050, "Product_Name": "Tennis Ball", "Category": "Sports", "Price_USD": 360, "Quantity_Sold": 5, "Total_Sales_USD": 1800, "Order_Date": "2025-01-16", "Customer_City": "Islamabad"}
];
